CREATE PROCEDURE [dbo].[TituloEliminar]
	@Id_Titulo INT
AS
	BEGIN
		SET NOCOUNT ON
		BEGIN TRANSACTION TRASA
			BEGIN TRY
				--METODO
				DELETE FROM Titulos WHERE Id_Titulo=@Id_Titulo
				COMMIT TRANSACTION TRASA
					SELECT 0 AS CodeError,'' AS MsgErr
			END TRY
			BEGIN CATCH
				SELECT ERROR_NUMBER() AS CodeError, ERROR_MESSAGE() AS MsgErr
				ROLLBACK TRANSACTION TRASA
			END CATCH
	END
